[phases.setup]
nixpkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[healthcheck]
path = "/api/health"
port = 8080
timeout = 10
interval = 15
retries = 5
